VAR internal
i	UINT			False	False	
n	UINT			False	False	
startPos	UINT			False	False	
endPos	UINT			False	False	
curIndex	UINT			False	False	
resultLen	UINT			False	False	
sCh	STRING[2]			False	False	
VAR IN/OUT
EN	Input	BOOL	No Edge		False	False	
InText	Input	STRING[512]	No Edge		False	False	
Index	Input	UINT	No Edge		False	False	
Delim	Input	STRING[2]	No Edge		False	False	
VAR RETURN
IDECON_FieldAt	STRING[255]					
